/**
 * Interface cho các bộ lọc của Detector
 */
interface DetectorFilter {
  id: string;
  enabled: number;
  filter_name: string;
  where: Array<{
    p1: string;
    p2: string;
    p3: string;
    p4: string;
  }>;
  actions: {
    halt: number;
    save: string;
    indifference: string;
    webhook: string;
    command: string;
    record: string;
    emailClient: string;
    global_webhook: string;
  };
}

/**
 * Interface cho cấu hình chi tiết của Monitor
 */
interface MonitorDetails {
  max_keep_days: string;
  notes: string;
  dir: string;
  ptz_id: string;
  auto_compress_videos: boolean | null;
  geolocation: string;
  rtmp_key: string;
  auto_host_enable: string; // "0" hoặc "1"
  auto_host: string;
  rtsp_transport: 'tcp' | 'udp' | string;
  muser: string;
  mpass: string;
  port_force: string;
  fatal_max: string;
  skip_ping: boolean | null;
  is_onvif: boolean | null;
  onvif_port: string;
  primary_input: string;
  aduration: string;
  probesize: string;
  stream_loop: string;
  sfps: string;
  wall_clock_timestamp_ignore: boolean | null;
  accelerator: string;
  hwaccel: string;
  hwaccel_vcodec: string;
  hwaccel_device: string;
  hwaccel_format: string;
  stream_type: 'hls' | 'mjpeg' | 'flv' | string;
  stream_flv_type: string;
  stream_flv_maxLatency: string;
  stream_mjpeg_clients: string;
  stream_vcodec: string;
  stream_acodec: string;
  hls_time: string;
  hls_list_size: string;
  preset_stream: string;
  stream_quality: string;
  stream_fps: string;
  stream_scale_x: string;
  stream_scale_y: string;
  stream_rotate: any;
  signal_check: string;
  signal_check_log: string;
  stream_vf: string;
  tv_channel: string;
  tv_channel_id: string;
  tv_channel_group_title: string;
  stream_timestamp: string;
  stream_timestamp_font: string;
  stream_timestamp_font_size: string;
  stream_timestamp_color: string;
  stream_timestamp_box_color: string;
  stream_timestamp_x: string;
  stream_timestamp_y: string;
  stream_watermark: string;
  stream_watermark_location: string;
  stream_watermark_position: string;
  snap: string;
  snap_fps: string;
  snap_scale_x: string;
  snap_scale_y: string;
  snap_vf: string;
  vcodec: string;
  crf: string;
  preset_record: string;
  acodec: string;
  record_scale_y: string;
  record_scale_x: string;
  cutoff: string;
  rotate: any;
  vf: string;
  timestamp: string;
  timestamp_font: string;
  timestamp_font_size: string;
  timestamp_color: string;
  timestamp_box_color: string;
  timestamp_x: string;
  timestamp_y: string;
  watermark: string;
  watermark_location: string;
  watermark_position: string;
  record_timelapse: any;
  record_timelapse_mp4: any;
  record_timelapse_fps: any;
  record_timelapse_scale_x: string;
  record_timelapse_scale_y: string;
  record_timelapse_vf: string;
  record_timelapse_watermark: any;
  record_timelapse_watermark_location: string;
  record_timelapse_watermark_position: any;
  detector: string;
  onvif_events: string;
  detector_save: string;
  use_detector_filters: string;
  use_detector_filters_object: string;
  detector_record_method: string;
  detector_trigger: string;
  detector_buffer_seconds_before: string;
  detector_timeout: string;
  watchdog_reset: string;
  detector_delete_motionless_videos: string;
  det_trigger_tags: string;
  detector_http_api: any;
  detector_send_frames: string;
  detector_fps: string;
  detector_scale_x: string;
  detector_scale_y: string;
  detector_lock_timeout: string;
  detector_send_video_length: string;
  snap_seconds_inward: string;
  cords: string; // JSON string "[]"
  detector_filters: Record<string, DetectorFilter>;
  detector_pam: string;
  detector_motion_save_frame: string;
  detector_sensitivity: string;
  detector_max_sensitivity: string;
  detector_threshold: string;
  detector_color_threshold: string;
  inverse_trigger: any;
  detector_frame: string;
  detector_motion_tile_mode: any;
  detector_tile_size: string;
  detector_noise_filter: any;
  detector_noise_filter_range: string;
  detector_use_detect_object: string;
  detectors_selected: any[];
  detector_object_ignore_not_move: any;
  detector_object_move_percent: string;
  detector_send_frames_object: any;
  detector_obj_count_in_region: any;
  detector_obj_region: any;
  detector_use_motion: string;
  detector_fps_object: string;
  detector_scale_x_object: string;
  detector_scale_y_object: string;
  detectorLineCounter: any;
  detectorLineCounterTags: string;
  detector_buffer_vcodec: string;
  detector_buffer_acodec: any;
  detector_buffer_fps: string;
  event_record_scale_x: string;
  event_record_scale_y: string;
  event_record_aduration: string;
  event_record_probesize: string;
  detector_record_overlap: any;
  detector_audio: any;
  detector_audio_min_db: string;
  detector_audio_max_db: string;
  detectorEventPtz: any;
  detector_webhook: string;
  detector_webhook_timeout: string;
  detector_webhook_url: string;
  detector_webhook_method: any;
  detector_command_enable: string;
  detector_command: string;
  detector_command_timeout: string;
  detector_notrigger: string;
  detector_notrigger_timeout: string;
  detector_notrigger_discord: any;
  detector_notrigger_webhook: any;
  detector_notrigger_webhook_url: string;
  detector_notrigger_webhook_method: any;
  detector_notrigger_command_enable: any;
  detector_notrigger_command: string;
  detector_notrigger_command_timeout: string;
  control: string;
  control_base_url: string;
  control_url_method: string;
  onvif_non_standard: string;
  control_digest_auth: any;
  control_axis_lock: string;
  control_stop: string;
  control_url_stop_timeout: string;
  control_turn_speed: string;
  detector_ptz_follow: string;
  detector_ptz_follow_target: string;
  control_url_center: string;
  control_url_left: string;
  control_url_left_stop: string;
  control_url_right: string;
  control_url_right_stop: string;
  control_url_up: string;
  control_url_up_stop: string;
  control_url_down: string;
  control_url_down_stop: string;
  control_url_enable_nv: string;
  control_url_disable_nv: string;
  control_url_zoom_out: string;
  control_url_zoom_out_stop: string;
  control_url_zoom_in: string;
  control_url_zoom_in_stop: string;
  control_invert_y: any;
  notify_global_webhook: any;
  notify_emailClient: any;
  notify_onUnexpectedExit: any;
  notify_useRawSnapshot: any;
  detector_emailClient_timeout: string;
  cust_input: string;
  cust_stream: string;
  cust_snap: string;
  cust_snap_raw: string;
  cust_record: string;
  cust_detect: string;
  cust_detect_object: string;
  cust_sip_record: string;
  custom_output: string;
  loglevel: string;
  sqllog: string;
  substream: {
    input: {
      type: string;
      stream_flv_type: any;
      fulladdress: string;
      sfps: string;
      aduration: string;
      probesize: string;
      stream_loop: any;
      rtsp_transport: string;
      accelerator: string;
      hwaccel: any;
      hwaccel_vcodec: string;
      hwaccel_device: string;
      cust_input: string;
    };
    output: {
      stream_type: string;
      stream_mjpeg_clients: string;
      stream_vcodec: string;
      stream_acodec: string;
      hls_time: string;
      hls_list_size: string;
      preset_stream: string;
      stream_quality: string;
      stream_v_br: string;
      stream_a_br: string;
      stream_fps: string;
      stream_scale_x: string;
      stream_scale_y: string;
      stream_rotate: any;
      svf: string;
      cust_stream: string;
    };
  };
  input_maps: any[];
  input_map_choices: Record<string, any[]>;
  stream_channels: any[];
  triggerMonitorsPtzTargets: Record<string, any>;
  detectorLineCounterSettings: {
    upName: string;
    downName: string;
    resetDaily: boolean;
  };
}

/**
 * Root Interface: MonitorType
 */
export interface MonitorType {
  ke: string;
  mid: string;
  name: string;
  details: MonitorDetails;
  type: string;
  ext: string;
  protocol: string;
  host: string;
  path: string;
  port: number;
  fps: number;
  mode: 'stop' | 'start' | string;
  width: number;
  height: number;
  saveDir: string | null;
  tags: string;
  currentlyWatching: number;
  status: string;
  code: string;
  subStreamActive: boolean;
  streams: string[];
  streamsSortedByType: Record<string, string[]>;
}
